spring:
  datasource:
    url: jdbc:postgresql://postgres:HGmXqTGYGvVTDFBWNnjNWZGEHcjgqGZj@mainline.proxy.rlwy.net:30992/railway
    username: postgres
    password: HGmXqTGYGvVTDFBWNnjNWZGEHcjgqGZj
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


